feat: APPS-2955 remaining components
UCLALibrary/ftva-website-nuxt pull request #43
Opened 2024-09-26 19:45 UTC by farosFreed

Connected to [APPS-2955](https://jira.library.ucla.edu/browse/APPS-2955)

**Page/Pages Created/updated:** /blog/[slug].vue from APPS-2955

**Notes:**

In progress

**Time Report:**

3 hours so far

**Checklist:**

-   [X] I added github label for semantic versioning
-   [X] I double checked it looks like the designs
-   [X] I completed any required mobile breakpoint styling
-   [X] I completed any required hover state styling
-   [X] I included a working spec file
-   [X] I added notes above about how long it took to build this component
-   [ ] UX has reviewed this PR
-   [ ] I assigned this PR to someone to review

2024-10-01 23:00 UTC, pghorpade requested changes

2024-10-01 23:36 UTC, farosFreed commented on pages/blog/[slug].vue
> +// TODO should this data be changed to reflect current page URL? Moved somewhere else?
great idea, done

2024-10-01 23:37 UTC, farosFreed commented on pages/blog/[slug].vue
> +      // captionTitle: 'dfdsfs', // TODO do we need these? test without
cleaned this up

2024-10-02 18:50 UTC, pghorpade approved these changes
👍

2024-10-02 19:56 UTC, merged